source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"

# ActionCable for WebSockets
gem "actioncable", "~> 8.1"

# CORS for frontend
gem "rack-cors"

gem "tzinfo-data", platforms: %i[ windows jruby ]
